export const GAMES_CONFIG = {
  roulette: {
    name: 'Russian Roulette',
    description: '8-chamber cylinder, 1 live bullet. Shoot yourself for defense or aim at opponent.',
    totalChambers: 8,
    turnTimeoutSeconds: 15,
  },
  blackjack: {
    name: 'Blackjack Face-Up',
    description: 'Shared common deck, all cards dealt face-up. Closest to 21 without busting wins.',
    turnTimeoutSeconds: 20,
    decksCount: 1,
  },
  bridge: {
    name: 'Glass Bridge',
    description: 'Endless perilous steps over the abyss. Choose tempered glass or shatter and lose a life.',
    initialLives: 3,
    turnTimeoutSeconds: 20,
  },
  chrono: {
    name: 'Chrono Blind',
    description: 'Countdown plunges into darkness. Hit STOP closest to 0.00 without overshooting.',
    minDurationSeconds: 5.0,
    maxDurationSeconds: 8.0,
    minBlindThresholdSeconds: 2.0,
    maxBlindThresholdSeconds: 4.0,
    roundsToWin: 2,
    maxRounds: 3,
  },
  split: {
    name: 'Split or Steal',
    description: 'Prisoner\'s dilemma casino showdown. Cooperate for peace & shared 25% jackpot (12.5% each), or betray to steal 100% pot plus 20% temptation bounty.',
    choiceCountdownSeconds: 30,
    jackpotThresholdGram: 5.0,
    jackpotSplitBonusPercent: 25,
    jackpotStealBonusPercent: 20,
  },
  shotgun: {
    name: 'Cyber Shotgun',
    description: 'Buckshot roulette style cyber duel. 3 HP, 15s turn, tactical items (Saw, Ejector, Handcuffs, Inverter).',
    initialHp: 3,
    turnTimeoutSeconds: 15,
  },
  connect4: {
    name: 'Connect 4',
    description: '7x6 vertical strategic grid. Align 4 chips in a row (horizontal, vertical, diagonal) to win.',
    rows: 6,
    cols: 7,
    turnTimeoutSeconds: 10,
  },
} as const;
